### ISSUE TITLE
Bug : all letters are "disabled"

### ISSUE THREAD

**Issue by Akawan** [DukeAstar/DT_ListNav#1]
I have a table with three columns. The first is invisible.

in file jquery.dataTables.listnav.js, this code:

/ \* Init listnav fill li to show disabled and enable letters \* /

var = anNodes oDTTable.oApi._fnGetTrNodes (oDTSettings);
$ ("td: nth-child (" + (defaults.iIndex +1) + ")", anNodes) each (function () {.
me $ ul.append ("<li>" + $ (this) text () + "</ li>"..);
});

---> AnNodes contains a list of tr with 2 children (2 visible)

I filter of "iIndex = 2"

defaults.iIndex+1 doesn't exist, so I will not go into the loop.
So the class "disabled" is added to each letter.

But the rest of features work properly!

I just replace defaults.iIndex +1 by defaults.iIndex" and it works.

**Comment by DukeAstar** [comment]
Can you post a fiddle I don't reproduce your problem

How do you hide your column ?

**Comment by Akawan** [comment]
I hide my column with this method : 

"aoColumns": [
                                {
                                    "sName": "Id",
                                    "bSearchable": false,
                                    "bSortable": false,
                                    "bVisible": false
                                },
... ]

**Comment by DukeAstar** [comment]
Fix has been made in 3747167 

It's a quick fix, I will search for a little bit more, if I don't see a better solution.

**Comment by Akawan** [comment]
Thank you!
