### ISSUE TITLE
Error using with Server Side Processing

### ISSUE THREAD

**Issue by cardinalweb** [DukeAstar/DT_ListNav#2]
I seem to be getting an error "Uncaught TypeError: Cannot read property 'nTr' of undefined " which is happening on line 50 of jquery.dataTables.listnav.js

My example is located here:
http://host.cardinalweb.com/dt/

The error stops further execution. The only way i can clear the error is by making sure the total iTotalRecords value is exactly the same as the display length (showing 10 records). In my example iTotalRecords is 100 which causes the error. If i change that in the Data returned to 10 it works with no error. Hope you can figure it out. 

Awesome plugin thanks so much for the work on this!!

**Comment by cardinalweb** [comment]
Reverted back to the file 4 mos ago  and that seems to have fixed the issue.

**Comment by DukeAstar** [comment]
I'll take a look at your problem and give you back an answer asap

**Comment by DukeAstar** [comment]
I 've found the problem , you use server data, initially the plugin was build to work without the option bServerside.
That's why when the global count of rows is greater than the number of rows loaded there is an error.

To enable the letters, we need to know which letters are used and with a partial fragment of data it's not possible.

I've got this problem to solve in the past and rewrite the plugin with a callback who ask server the first letters.

If you are interested ask me .

**Comment by cardinalweb** [comment]
awesome thanks. really appreciate it

best
s

Stephen Holland-Chang
Chief Technology Officer / Cardinal Communications
stephen@cardinalweb.com
cardinalweb.com http://www.cardinalweb.com

From:  DukeAstar notifications@github.com
Reply-To:  DukeAstar/DT_ListNav
<reply+i-20144316-43fab29bacdf6f8743f76216125610307962164b-5275347@reply.git
hub.com>
Date:  Monday, September 30, 2013 3:59 AM
To:  DukeAstar/DT_ListNav DT_ListNav@noreply.github.com
Cc:  stephen holland-chang support@cardinalweb.com
Subject:  Re: [DT_ListNav] Error using with Server Side Processing (#2)

I'll take a look to your problem and give you back an answer asap

‹
Reply to this email directly or view it on GitHub
https://github.com/DukeAstar/DT_ListNav/issues/2#issuecomment-25351947 .

**Comment by DukeAstar** [comment]
Sorry for the late answer , take a look at the second version of the plugin.

There is no more any dependencies, and you can use a function to get the first letters.

If you need some help, ask for it.
