### ISSUE TITLE
Compatible with dataTables 1.10?

### ISSUE THREAD

**Issue by Soupy** [DukeAstar/DT_ListNav#4]
Are you planning to update this great plugin to be compatible with dataTables 1.10?

**Comment by DukeAstar** [comment]
Great tout learn that jdatatables passed to 1.10, I'll take a look at this version and upgrade if there are some problems. If you encounter problem dont hesitate to open an issue on your problem

**Comment by Soupy** [comment]
Well I've encountered an issue with the following line of your code:

```
                var anNodes = oDTTable.oApi._fnGetTrNodes( oDTSettings );
```

dataTables v1.10.beta 2 does not like the call to _fnGetTrNodes. Actually, the author (Allan) doesn't like anyone calling that function and others at all. You need to use the new dataTables API (rows().nodes() or something to that effect and its all beyond my knowledge :(

**Comment by DukeAstar** [comment]
Ok thanks for the reply, I try to take a look as soon as I can, It seems to be easy to fix,

One question, why are you using the version 1.10 which version is still in beta, so not to be put in production? I don't know when Allan planned to put in release version.

I'll make a fix , but it will be in a separate file , for 2 reasons , the first is to keep compatibility with current stable release of JDatatables, the second is that I dont know if allan will not change an API I'll use.

**Comment by Soupy** [comment]
Thank you for considering changing your code to work with dataTables 1.10.

I believe that Allan is planning to have v.1.10 available "soon". It is already in beta 2 and progressing. I want to be able to have some production code when he releases it and that's why I'm trying to get your plugin to work with it. 

I understand completely your reason for having to keep two versions of the ListNav available.

And I agree with you about the API. Allan has made manipulating datatables via the API a lot easier (for someone like yourself who knows jQuery).

**Comment by DukeAstar** [comment]
Hi, I 've commit the file and the plugin is now compatible with DataTable 1.10.
The part of code which has changed use the New API.

All the rest of code will be change later.

Don't hesitate to post your comments
