### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by austinmateka** [DukeAstar/DT_ListNav#5]
Hello,

I'm having some difficulty getting the ListNav plugin for DataTables to work. Im getting an error that says "DataTables warning: table id=table_1 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1"

The website is www.thekaraokyguy.ca/writings.

Can you help me out!

Thank you.

**Comment by DukeAstar** [comment]
Hello your site is unavailable, but it seems your ajax response is not json.

**Comment by austinmateka** [comment]
Hi Duke,

Sorry about that; I was troubleshooting a few things.

The table should be there now with the filter. Thankfully the JSON Error isn't popping up anymore, but it's filtering the "Song" column instead of the "Artist" column. There are some minor visual errors such as the double Entry and Search field.

If you can help me out, that would be incredible! And thank you so much.
